const app=document.querySelector('#app'), messages=document.querySelector('#messages'), input=document.querySelector('#input'), mode=document.querySelector('#mode'), thought=document.querySelector('#thought');
let voiceOn=true,isResponding=false; const conversationHistory=[];
const moodLines={entspannt:'Ganz ruhig. Erzähl.',flirty:'Mhm… ich höre. 😏',amüsiert:'Okay, jetzt bin ich neugierig. 😂',skeptisch:'Das kauf ich dir noch nicht ganz ab.',genervt:'Ay, por favor… was hast du jetzt gemacht?',ernst:'Okay. Ich bin bei dir. Kein Quatsch.'};
function add(text,who='sofia'){const d=document.createElement('div');d.className='msg '+who;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function speak(text){if(!voiceOn||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/[😏😂🙄]/g,''));u.lang='de-DE';u.rate=.96;u.pitch=1.08;u.onstart=()=>{app.dataset.speaking='true';mode.textContent='spricht…'};u.onend=()=>{app.dataset.speaking='false';mode.textContent='bereit'};speechSynthesis.speak(u)}
function applyMood(mood){const valid=['entspannt','flirty','amüsiert','skeptisch','genervt','ernst'];const next=valid.includes(mood)?mood:'entspannt';app.dataset.mood=next;document.querySelectorAll('[data-mood]').forEach(b=>b.classList.toggle('active',b.dataset.mood===next))}
async function respond(user){if(isResponding)return;isResponding=true;input.disabled=true;mode.textContent='denkt nach…';thought.textContent='…';try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:user,history:conversationHistory.slice(-16)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Sofia konnte nicht antworten.');const reply=data.reply||'Hm. Irgendwas ist gerade schiefgelaufen. 🙄';conversationHistory.push({role:'user',content:user},{role:'assistant',content:reply});if(conversationHistory.length>32)conversationHistory.splice(0,conversationHistory.length-32);applyMood(data.mood);add(reply);thought.textContent=reply;mode.textContent='bereit';speak(reply)}catch(error){console.error('Sofia API error:',error);const msg='Okay… die Verbindung zu meinem Kopf ist gerade weg. 🙄 Versuch es gleich nochmal.';add(msg);thought.textContent=msg;mode.textContent='Verbindungsfehler'}finally{isResponding=false;input.disabled=false;input.focus()}}
document.querySelector('#form').addEventListener('submit',e=>{e.preventDefault();const v=input.value.trim();if(!v||isResponding)return;add(v,'user');input.value='';respond(v)});
document.querySelectorAll('[data-mood]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-mood]').forEach(x=>x.classList.remove('active'));b.classList.add('active');app.dataset.mood=b.dataset.mood;thought.textContent=moodLines[b.dataset.mood];mode.textContent=b.dataset.mood}));
document.querySelector('#voiceToggle').onclick=e=>{voiceOn=!voiceOn;e.currentTarget.classList.toggle('active',voiceOn);if(!voiceOn&&'speechSynthesis'in window)speechSynthesis.cancel()};
document.querySelector('#mute').onclick=e=>{voiceOn=!voiceOn;e.currentTarget.classList.toggle('on',!voiceOn);if(!voiceOn&&'speechSynthesis'in window)speechSynthesis.cancel()};
document.querySelector('#focus').onclick=e=>{app.classList.toggle('focus');e.currentTarget.classList.toggle('on')};
document.querySelector('#camera').onclick=e=>{e.currentTarget.classList.toggle('on');thought.textContent=e.currentTarget.classList.contains('on')?'Kamera-Modus aktiv. 👀':'Kamera-Modus aus.'};
const mic=document.querySelector('#mic');const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const rec=new SR();rec.lang='de-DE';rec.interimResults=false;rec.onstart=()=>{mic.classList.add('active');mode.textContent='hört zu…'};rec.onend=()=>{mic.classList.remove('active');if(!isResponding)mode.textContent='bereit'};rec.onresult=e=>{input.value=e.results[0][0].transcript;document.querySelector('#form').requestSubmit()};mic.onclick=()=>rec.start()}else{mic.onclick=()=>{thought.textContent='Spracheingabe wird von diesem Browser nicht unterstützt.'}};
setInterval(()=>{document.querySelector('#clock').textContent=new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})},1000);document.querySelector('#clock').textContent=new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});
