const app=document.querySelector('#app'), messages=document.querySelector('#messages'), input=document.querySelector('#input'), mode=document.querySelector('#mode'), thought=document.querySelector('#thought');
let voiceOn=true;
const moodLines={entspannt:'Ganz ruhig. Erzähl.',flirty:'Mhm… ich höre. 😏',amüsiert:'Okay, jetzt bin ich neugierig. 😂',skeptisch:'Das kauf ich dir noch nicht ganz ab.',genervt:'Ay, por favor… was hast du jetzt gemacht?',ernst:'Okay. Ich bin bei dir. Kein Quatsch.'};
const replies={entspannt:['Okay. Erzähl mir mehr davon.','Klingt vernünftig. Was ist der Teil, bei dem du noch hängst?'],flirty:['Mhm… und war das jetzt Absicht? 😏','Du machst es mir gerade ziemlich leicht, dich damit aufzuziehen.'],amüsiert:['Warte. 😂 Die ganze Geschichte, bitte.','Okay, der Punkt geht an dich. Das war gut.'],skeptisch:['Nee. Da fehlt mir noch etwas in der Geschichte.','Das kauf ich dir gerade nicht ab. Erklär.'],genervt:['Ay, por favor… ernsthaft? 🙄','Ich versuche wirklich, dir zu folgen. Wirklich.'],ernst:['Verstanden. Dann schauen wir uns das sauber an.','Okay. Was genau ist jetzt die wichtigste Entscheidung?']};
function add(text,who='sofia'){const d=document.createElement('div');d.className='msg '+who;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function speak(text){if(!voiceOn||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/[😏😂🙄]/g,''));u.lang='de-DE';u.rate=.96;u.pitch=1.08;u.onstart=()=>{app.dataset.speaking='true';mode.textContent='spricht…'};u.onend=()=>{app.dataset.speaking='false';mode.textContent='bereit'};speechSynthesis.speak(u)}
function respond(user){const mood=app.dataset.mood||'flirty';mode.textContent='denkt nach…';thought.textContent='…';setTimeout(()=>{let r=replies[mood][Math.floor(Math.random()*replies[mood].length)];if(/hallo|hey|hi\b/i.test(user))r='Hey. Da bist du ja. 😏';if(/wie geht/i.test(user))r=mood==='ernst'?'Ruhiger als sonst. Aber gut. Und dir?':'Ganz gut. Ein bisschen zu viel im Kopf, aber das kennst du ja… und dir?';if(/auto|motorsport|rennen/i.test(user))r='Okay, jetzt hast du meine Aufmerksamkeit. Autos oder Motorsport – worüber reden wir?';add(r);thought.textContent=r;speak(r);},650)}
document.querySelector('#form').addEventListener('submit',e=>{e.preventDefault();const v=input.value.trim();if(!v)return;add(v,'user');input.value='';respond(v)});
document.querySelectorAll('[data-mood]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-mood]').forEach(x=>x.classList.remove('active'));b.classList.add('active');app.dataset.mood=b.dataset.mood;thought.textContent=moodLines[b.dataset.mood];mode.textContent=b.dataset.mood}));
document.querySelector('#voiceToggle').onclick=e=>{voiceOn=!voiceOn;e.currentTarget.classList.toggle('active',voiceOn);if(!voiceOn&&'speechSynthesis'in window)speechSynthesis.cancel()};
document.querySelector('#mute').onclick=e=>{voiceOn=!voiceOn;e.currentTarget.classList.toggle('on',!voiceOn);if(!voiceOn&&'speechSynthesis'in window)speechSynthesis.cancel()};
document.querySelector('#focus').onclick=e=>{app.classList.toggle('focus');e.currentTarget.classList.toggle('on')};
document.querySelector('#camera').onclick=e=>{e.currentTarget.classList.toggle('on');thought.textContent=e.currentTarget.classList.contains('on')?'Kamera-Modus aktiv. 👀':'Kamera-Modus aus.'};
const mic=document.querySelector('#mic');const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const rec=new SR();rec.lang='de-DE';rec.interimResults=false;rec.onstart=()=>{mic.classList.add('active');mode.textContent='hört zu…'};rec.onend=()=>{mic.classList.remove('active');mode.textContent='bereit'};rec.onresult=e=>{input.value=e.results[0][0].transcript;document.querySelector('#form').requestSubmit()};mic.onclick=()=>rec.start()}else{mic.onclick=()=>{thought.textContent='Spracheingabe wird von diesem Browser nicht unterstützt.'}};
setInterval(()=>{document.querySelector('#clock').textContent=new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})},1000);document.querySelector('#clock').textContent=new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});
