/* Sofia 4.65.7 — read-only Hamburg day overview; actions require a user gesture. */
(() => {
  const KEY='sofia_today_sections_v465';
  const sections=['messages','photos','tasks','topics'];
  const normalize=value=>Object.fromEntries(sections.map(key=>[key,value?.[key]!==false]));
  const day=value=>{if(value===null||value===undefined||value==='')return null;const date=new Date(value);if(!Number.isFinite(+date))return null;return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);};
  const time=value=>new Date(value).toLocaleString('de-DE',{timeZone:'Europe/Berlin',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
  function model({images=[],tasks=[],life=null}={},now=new Date()){
    const today=day(now),seen=new Set();
    return {day:today,overdue:tasks.filter(x=>x.status==='open'&&day(x.dueAt||x.remindAt)&&day(x.dueAt||x.remindAt)<today).sort((a,b)=>Date.parse(a.dueAt||a.remindAt)-Date.parse(b.dueAt||b.remindAt)),photos:images.filter(x=>x&&x.id&&!['pending','failed','expired'].includes(x.status)&&x.published!==false&&!x.deleted&&day(x.sentAt||x.createdAt)===today&&!seen.has(x.id)&&seen.add(x.id)).sort((a,b)=>Date.parse(b.sentAt||b.createdAt)-Date.parse(a.sentAt||a.createdAt)),tasks:tasks.filter(x=>x.status==='open'&&day(x.dueAt||x.remindAt)===today).sort((a,b)=>Date.parse(a.dueAt||a.remindAt)-Date.parse(b.dueAt||b.remindAt)),topics:(life?.threads||[]).filter(x=>x.status==='open'&&Date.parse(x.expiresAt)>+now).slice(-6).reverse()};
  }
  let prefs;try{prefs=normalize(JSON.parse(localStorage.getItem(KEY)));}catch{prefs=normalize();}
  let data={images:[],tasks:[],life:null,history:[]},loading=null,errors={chat:false,tasks:false};
  const countLabel=(n,one,many)=>n+' '+(n===1?one:many);
  const button=(text,action)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=action;return b;};
  function panel(title){const d=document.createElement('dialog');d.className='workspace-dialog today-dialog';const h=document.createElement('h2');h.textContent=title;const close=button('Schließen',()=>d.close());d.append(h,close);document.body.append(d);window.SofiaUI?.enhanceDialog(d,title);d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();close.focus();return d;}
  async function refresh(){
    if(loading)return loading;
    loading=(async()=>{const results=await Promise.allSettled(['/api/chat','/api/tasks?status=open'].map(async url=>{const r=await fetch(url,{credentials:'same-origin',cache:'no-store',signal:typeof AbortSignal!=='undefined'&&AbortSignal.timeout?AbortSignal.timeout(12000):undefined});if(!r.ok)throw Error();return r.json();}));let complete=true;for(let i=0;i<results.length;i++){const result=results[i];const key=i===0?'chat':'tasks';errors[key]=false;if(result.status!=='fulfilled'){complete=false;errors[key]=true;continue;}const value=result.value;if(i===0&&Array.isArray(value.images)){data={...data,images:value.images,life:value.life,history:Array.isArray(value.history)?value.history:[]};}else if(i===1&&Array.isArray(value.tasks)){data={...data,tasks:value.tasks};}else{complete=false;errors[key]=true;}}return complete;})();
    try{return await loading;}finally{loading=null;}
  }
  function settings(parent,render){const d=panel('Heute einstellen');const note=document.createElement('p');note.textContent='Bereiche auf diesem Gerät anzeigen:';d.append(note);const status=document.createElement('p');status.setAttribute('role','status');for(const [key,text]of [['messages','Neue Nachrichten'],['photos','Fotos von heute'],['tasks','Heute fällige Aufgaben'],['topics','Weiterreden']]){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=prefs[key];input.onchange=()=>{prefs={...prefs,[key]:input.checked};try{localStorage.setItem(KEY,JSON.stringify(prefs));status.textContent='Auswahl gespeichert.';}catch{status.textContent='Auswahl konnte nicht gespeichert werden.';}if(parent.isConnected)render();};label.append(input,document.createTextNode(' '+text));d.append(label);}d.append(status);}
  function taskDetail(task){const d=panel(task.title);d.dataset.taskId=task.id;const text=document.createElement('p');text.className='today-task-detail';text.textContent='Fällig: '+time(task.dueAt||task.remindAt)+(task.remindAt?'\nErinnerung: '+time(task.remindAt):'')+'\nPriorität: '+({high:'Hoch',low:'Niedrig',normal:'Normal'}[task.priority]||'Normal')+(task.notes?'\n'+task.notes:'');d.append(text,button('Schließen',()=>d.close()));}
  function unread(){const local=window.SofiaWorkspace?.unreadMessages?.()||[],contacts=window.SofiaSocial?.unreadMessages?.()||[];return [...local.filter(x=>!x.contactId),...contacts.map(x=>({...x,contactId:x.id,content:x.text,role:'assistant'}))];}
  function open(){const existing=document.getElementById('sofia-today');if(existing){existing.focus();return;}const d=panel('Heute · '+time(new Date()).slice(0,10));d.id='sofia-today';const status=document.createElement('p');status.setAttribute('role','status');const content=document.createElement('div');const summary=document.createElement('p');summary.className='today-summary';d.append(summary);d.append(button('Bereiche auswählen',()=>settings(d,render)),status,content);
    function section(title,items,label,action){const area=document.createElement('section'),h=document.createElement('h3');h.textContent=title;area.append(h);const affected=/Aufgaben/.test(title)?errors.tasks:!/^Neue Nachrichten/.test(title)&&errors.chat;if(affected){const note=document.createElement('p');note.className='today-section-warning';note.textContent='Dieser Bereich konnte nicht aktualisiert werden. Vorhandene Einträge können veraltet sein.';area.append(note);}if(!items.length){const empty=document.createElement('p');empty.textContent='Zurzeit keine Einträge.';area.append(empty);}for(const item of items)area.append(button(label(item),()=>action(item)));content.append(area);}
    function render(){content.replaceChildren();const draft=document.getElementById('input')?.value?.trim();if(draft){const box=document.createElement('section');box.className='today-draft';const text=document.createElement('p');text.textContent='Ungesendeter Entwurf: '+draft.slice(0,180);box.append(text,button('Entwurf fortsetzen',()=>{d.close();window.SofiaChatViewport?.reveal?.();document.getElementById('input')?.focus();}));content.append(box);}const view=model(data);const messages=unread();summary.textContent=[prefs.messages?countLabel(messages.length,'neue Nachricht','neue Nachrichten'):null,prefs.photos?countLabel(view.photos.length,'Foto','Fotos'):null,prefs.tasks?countLabel(view.tasks.length+view.overdue.length,'Aufgabe','Aufgaben'):null,prefs.topics?countLabel(view.topics.length,'Gesprächsthema','Gesprächsthemen'):null].filter(Boolean).join(' · ')||'Alle Bereiche sind ausgeblendet. Über „Bereiche auswählen“ kannst du sie wieder anzeigen.';if(prefs.messages)section('Neue Nachrichten ('+(window.SofiaSocial?.unreadCount?.()??unread().length)+')',unread(),x=>time(x.createdAt)+' · '+String(x.content||'Neue Nachricht').slice(0,180),x=>{d.close();if(x.contactId){window.dispatchEvent(new CustomEvent('sofia-contact-open',{detail:{contactId:x.contactId}}));}else requestAnimationFrame(()=>{if(!window.SofiaWorkspace?.showMessage(x))window.SofiaWorkspace?.notice('Diese Nachricht ist im geladenen Verlauf nicht mehr enthalten.');});});if(prefs.photos)section('Fotos von heute',view.photos,x=>time(x.sentAt||x.createdAt)+' · '+(x.sourceId?'Fotovariante öffnen':'Foto öffnen'),x=>{d.close();window.SofiaImages?.openGallery(x.id);});if(prefs.tasks&&view.overdue.length)section('Überfällige Aufgaben',view.overdue,x=>time(x.dueAt||x.remindAt)+' · '+x.title,taskDetail);if(prefs.tasks)section('Deine heute fälligen Aufgaben',view.tasks,x=>time(x.dueAt||x.remindAt)+' · '+x.title,taskDetail);if(prefs.topics)section('Offene Fragen von Sofia',(data.life?.dialogue?.questions||[]).filter(q=>q.status==='open'&&Date.parse(q.at)>Date.now()-86400000).slice(-4),q=>q.text,q=>{const turn=data.history.find(t=>t.role==='assistant'&&t.content.includes(q.text));if(!turn){status.textContent='Die Frage ist nicht mehr im geladenen Verlauf.';return;}if(window.SofiaWorkspace?.selectReply(turn))d.close();});if(prefs.topics)section('Weiterreden',view.topics,x=>x.topic||x.text,x=>{const input=document.getElementById('input');if(!input||input.value.trim()){status.textContent='Es ist bereits ein Entwurf vorhanden. Bitte zuerst abschicken oder sichern.';return;}input.value='Lass uns über '+String(x.topic||x.text).slice(0,180)+' weiterreden.';window.SofiaWorkspace?.saveDraft();window.SofiaUI?.resizeComposer(input);d.close();window.SofiaChatViewport?.reveal?.();input.focus();});}
    const refreshButton=button('Aktualisieren',()=>void load());render();const load=async()=>{refreshButton.disabled=true;content.setAttribute('aria-busy','true');status.textContent='Übersicht wird aktualisiert …';refreshButton.setAttribute('aria-label','Heute aktualisieren');const ok=await refresh();if(!d.isConnected)return;refreshButton.disabled=false;content.setAttribute('aria-busy','false');render();status.textContent=ok?'Stand: '+time(new Date()):'Nicht vollständig aktualisiert ('+[errors.chat?'Fotos und Gesprächsthemen':null,errors.tasks?'Aufgaben':null].filter(Boolean).join(', ')+'). Bereits geladene Einträge bleiben verfügbar; es werden keine Aktionen automatisch wiederholt.';};d.append(refreshButton,button('Schließen',()=>d.close()));void load();
    const repaint=()=>{if(d.isConnected)render();};window.addEventListener('sofia-unread-updated',repaint);window.addEventListener('sofia-social-state-changed',repaint);d.addEventListener('close',()=>{window.removeEventListener('sofia-unread-updated',repaint);window.removeEventListener('sofia-social-state-changed',repaint);},{once:true});
  }
  window.SofiaToday={open,model,normalize,day,refresh};
})();

