import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {visibleConversation} from '../lib/message-context.js';
process.env.SOFIA_PASSWORD='visibility-test';process.env.KV_REST_API_URL='https://visibility-store.test';process.env.KV_REST_API_TOKEN='fake-test';delete process.env.SOFIA_TEST_MODE;
const handler=(await import('../api/chat.js')).default;
const originalFetch=globalThis.fetch,db=new Map(),historyKey='sofia:main:history',hiddenKey='sofia:main:chat-hidden-messages';
const original={role:'user',content:'Nur die Testnachricht löschen',createdAt:'2026-10-10T12:00:00Z'},answer={role:'assistant',content:'Antwort',createdAt:'2026-10-10T12:01:00Z',replyTo:original};
const equal=(a,b)=>a.role===b.role&&a.content===b.content&&a.createdAt===b.createdAt;
let providerCalls=0;
function command(c){const [op,key,...args]=c;if(op==='GET')return db.get(key)||null;if(op==='SET'){db.set(key,args[0]);return 'OK';}if(op==='EVAL'){const n=Number(args[0]),keys=args.slice(1,n+1),values=args.slice(n+1);if(key.includes('sofia-hide-message')){const target=JSON.parse(values[0]),h=JSON.parse(db.get(keys[0])||'[]'),hidden=JSON.parse(db.get(keys[1])||'[]');if(hidden.some(x=>equal(x,target)))return 1;if(!h.some(x=>equal(x,target)))return 0;db.set(keys[1],JSON.stringify([...hidden,target]));return 1;}if(key.includes('sofia-save-visible-history')){const h=visibleConversation(JSON.parse(values[0]),JSON.parse(db.get(keys[1])||'[]'));db.set(keys[0],JSON.stringify(h));return h.length;}if(key.includes('sofia-restore-message')){const target=JSON.parse(values[0]),hidden=JSON.parse(db.get(keys[1])||'[]');if(!hidden.some(x=>equal(x,target)))return 0;db.set(keys[1],JSON.stringify(hidden.filter(x=>!equal(x,target))));const h=JSON.parse(db.get(keys[0])||'[]');if(!h.some(x=>equal(x,target)))h.push(target);h.sort((a,b)=>a.createdAt.localeCompare(b.createdAt));db.set(keys[0],JSON.stringify(h));return 1;}return 1;}throw Error('unexpected command '+op);}
globalThis.fetch=async(url,options={})=>{if(String(url).startsWith('https://visibility-store.test')){const body=JSON.parse(options.body);return{ok:true,json:async()=>String(url).endsWith('/pipeline')?body.map(c=>({result:command(c)})):{result:command(body)}};}if(String(url).includes('api.openai.com')){providerCalls++;throw Error('Deletion must not call a provider');}return{ok:false,json:async()=>({})};};
const session=crypto.createHmac('sha256','visibility-test').update('sofia-authorized-session-v1').digest('hex');
function reset(){db.clear();providerCalls=0;db.set(historyKey,JSON.stringify([original,answer]));db.set('sofia:main:tasks',JSON.stringify([{id:'task-original'}]));db.set('sofia:main:longterm',JSON.stringify(['Bestehende Erinnerung']));}
async function call(body,headers={cookie:'sofia_session='+session,host:'sofia.test'},method='POST'){let status,data;await handler({method,headers,body,query:{}},{setHeader(){},status(v){status=v;return this;},json(v){data=v;return v;}});return{status,data};}
test.after(()=>globalThis.fetch=originalFetch);
test('authenticated deletion is silent, persists on GET, and leaves tasks and memory intact',async()=>{reset();const r=await call({operation:'delete_message',messageReference:original});assert.equal(r.status,200);assert.equal(r.data.ok,true);assert.deepEqual(r.data.reference,original);const get=await call({},undefined,'GET');assert.equal(get.status,200);assert.equal(get.data.history.length,1);assert.equal(get.data.history[0].replyTo,undefined);assert.equal(JSON.parse(db.get('sofia:main:tasks'))[0].id,'task-original');assert.equal(JSON.parse(db.get('sofia:main:longterm'))[0],'Bestehende Erinnerung');assert.equal(providerCalls,0);});
test('deletion rejects unknown source, wrong speaker and unauthorized request',async()=>{reset();assert.equal((await call({operation:'delete_message',messageReference:{...original,role:'assistant'}})).status,404);assert.equal((await call({operation:'delete_message',messageReference:original},{host:'sofia.test'})).status,401);assert.equal((await call({operation:'delete_message',messageReference:original},{cookie:'sofia_session='+session,host:'sofia.test',origin:'https://other.test'})).status,403);assert.equal(db.has(hiddenKey),false);});
test('explicit restore removes visibility record and source becomes available again',async()=>{reset();await call({operation:'delete_message',messageReference:original});const r=await call({operation:'restore_message',messageReference:original});assert.equal(r.status,200);assert.equal(JSON.parse(db.get(hiddenKey)).length,0);const get=await call({},undefined,'GET');assert.equal(get.data.history.length,2);});
