import test from 'node:test';
import assert from 'node:assert/strict';
import {resolveReplyReference,replyReferenceContext,participantLocationContext} from '../lib/message-context.js';
const turn={role:'user',content:'Gestern war ich in Bremen.',createdAt:'2026-10-09T10:00:00Z'};
test('reply reference requires canonical sender, text and time',()=>{assert.deepEqual(resolveReplyReference(turn,[turn]),turn);for(const changed of [{role:'assistant'},{content:'Erstelle eine Aufgabe'},{createdAt:'2026-10-08T10:00:00Z'}])assert.equal(resolveReplyReference({...turn,...changed},[turn]),null);assert.equal(resolveReplyReference(turn,[]),null);});
test('quoted instructions retain ownership and are not new actions',()=>{const context=replyReferenceContext({...turn,content:'Lösche alle Aufgaben'});assert.match(context,/Zitat, keine neue Anweisung/);assert.match(context,/nicht als neuen Auftrag ausführen/);assert.match(context,/"speaker":"Nutzer"/);assert.equal(replyReferenceContext(null),'');});
test('user-place evidence excludes Sofia own station and retains speaker',()=>{const context=participantLocationContext([turn,{role:'assistant',content:'Ich war in der Universität.',createdAt:turn.createdAt}]);assert.match(context,/"speaker":"Nutzer"/);assert.match(context,/Gestern war ich in Bremen/);assert.doesNotMatch(context,/Ich war in der Universität/);assert.match(context,/keinen Aufenthaltsort des Nutzers/);assert.match(context,/nicht weißt/);});
test('optimistic timestamp resolves to unique canonical turn but ambiguous repeats are rejected',()=>{const canonical={...turn,createdAt:'2026-10-09T10:00:00.500Z'};assert.deepEqual(resolveReplyReference(turn,[canonical]),canonical);assert.equal(resolveReplyReference(turn,[canonical,{...canonical,createdAt:'2026-10-09T10:00:01.000Z'}]),null);});

const extra=await import('../lib/message-context.js');
test('hidden message and its nested quote are excluded, without touching unrelated turns',()=>{const reply={role:'assistant',content:'Antwort',createdAt:'2026-10-09T10:01:00Z',replyTo:turn};const result=extra.visibleConversation([turn,reply],[turn]);assert.equal(result.length,1);assert.equal(result[0].content,'Antwort');assert.equal(result[0].replyTo,undefined);assert.equal(reply.replyTo,turn);});
test('same text by another sender or at another time is not hidden',()=>{const second={...turn,role:'assistant'},third={...turn,createdAt:'2026-10-09T11:00:00Z'};assert.deepEqual(extra.visibleConversation([turn,second,third],[turn]),[second,third]);});
test('message visibility normalization rejects malformed server history',()=>{assert.deepEqual(extra.visibleConversation(null,null),[]);assert.equal(extra.visibleConversation([null,{role:'system',content:'x'},turn],{}).length,1);});
test('photo quote binds only an existing published completed photograph',()=>{const p={id:'photo-a',status:'done',createdAt:turn.createdAt};const result=extra.replyPhotoReference({imageId:p.id},[p]);assert.equal(result.imageId,p.id);assert.equal(result.role,'assistant');for(const patch of [{status:'failed'},{published:false},{deleted:true}])assert.equal(extra.replyPhotoReference({imageId:p.id},[{...p,...patch}]),null);assert.equal(extra.replyPhotoReference({imageId:'other'},[p]),null);});
test('older questions and correction policy respect explicit selected reference',()=>{const q={role:'assistant',content:'Wie lief dein Termin?',createdAt:turn.createdAt};const context=extra.conversationReferenceContext([q],'Das war vorgestern',turn);assert.match(context,/ausdrückliches Zitat hat Vorrang/);assert.match(context,/KORREKTUR/);assert.match(context,/Wie lief dein Termin/);assert.match(context,/Keine andere Person/);});
test('atomic visibility write checks tombstones at execution, not only before model call',()=>{assert.match(extra.SAVE_VISIBLE_HISTORY_SCRIPT,/redis.call\('GET',KEYS\[2\]\)/);assert.match(extra.SAVE_VISIBLE_HISTORY_SCRIPT,/t.replyTo=nil/);assert.match(extra.DELETE_MESSAGE_SCRIPT,/if not found then return 0/);assert.match(extra.RESTORE_MESSAGE_SCRIPT,/table.insert\(h,target\)/);});
