import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import crypto from 'node:crypto';
const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const environment=url(await readFile(new URL('../lib/environment.js',import.meta.url),'utf8'));
const character=url((await readFile(new URL('../lib/character-image.js',import.meta.url),'utf8')).replaceAll('../lib/environment.js',environment));
const api=await import(character);
const engine=url('export async function executeUnifiedAction(){throw Error("Unexpected task execution")} export async function getActionState(){return {}} export async function getResearchState(){return {}}');
async function handler(file){return (await import(url((await readFile(new URL('../api/'+file,import.meta.url),'utf8')).replaceAll('../lib/environment.js',environment).replaceAll('../lib/character-image.js',character).replaceAll('./action-engine.js',engine)))).default;}
const chat=await handler('chat.js'),live=await handler('live-context.js'),memory=await handler('memory.js');
const prefix='sofia:main:portrait:',savedFetch=globalThis.fetch,keys=['KV_REST_API_URL','KV_REST_API_TOKEN','OPENAI_API_KEY','SOFIA_PASSWORD','SOFIA_TEST_MODE'],env=Object.fromEntries(keys.map(k=>[k,process.env[k]]));
let db,commands;
function reset(){db=new Map();commands=[];process.env.KV_REST_API_URL='https://projects.test';process.env.KV_REST_API_TOKEN='test';process.env.OPENAI_API_KEY='test';process.env.SOFIA_PASSWORD='test';delete process.env.SOFIA_TEST_MODE;}
globalThis.fetch=async(endpoint,options)=>{assert.equal(endpoint,'https://projects.test');const args=JSON.parse(options.body);commands.push(args);const [op,key,value]=args;let result;
 if(op==='GET')result=db.get(key)||null;
 else if(op==='SET'){db.set(key,value);result='OK';}
 else if(op==='EVAL'&&/sofia-(?:project|life|memory)-cas/.test(key)){const target=args[3];result=(db.get(target)||'')===args[4]?1:0;if(result)db.set(target,args[5]);}
 else if(op==='EVAL'&&key.startsWith('local h=')){result=1;}
 else throw Error('Unexpected command '+op);
 return {ok:true,json:async()=>({result})};
};
test.after(()=>{globalThis.fetch=savedFetch;for(const k of keys)if(env[k]===undefined)delete process.env[k];else process.env[k]=env[k];});
async function create(title='Testumzug'){return api.editProject({operation:'create',revision:(await api.projectState()).revision,value:title});}
function request(message){return {method:'POST',headers:{cookie:'sofia_session='+crypto.createHmac('sha256','test').update('sofia-authorized-session-v1').digest('hex')},body:{message}};}
async function call(fn,req){const res={code:200,setHeader(){},status(n){this.code=n;return this;},json(data){this.data=data;return this;}};await fn(req,res);return res;}
test('explicit project creates once, selects it, and persists across multiple calendar days',async()=>{reset();const a=await api.executeProjectCommand('Lass uns meinen Testumzug planen.');assert.match(a.reply,/angelegt/);const b=await api.executeProjectCommand('Lass uns meinen Testumzug planen.');assert.equal(b.state.items.length,1);assert.equal(b.state.revision,a.state.revision);assert.equal((await api.projectState()).items[0].status,'active');assert.equal(commands.filter(x=>x[0]==='SET'&&x[1].endsWith('tasks')).length,0);});
test('ideas, negatives, quotes and ordinary conversation cannot create projects',async()=>{reset();for(const text of ['Ich könnte irgendwann umziehen.','Lass uns meinen Umzug später planen.','Lass uns meinen Umzug nicht planen.','Was hältst du von einem Umzug?','„Lass uns meinen Umzug planen“ ist nur ein Beispiel.'])assert.equal(await api.executeProjectCommand(text),null);assert.equal(commands.length,0);});
test('goals decisions and questions belong to the user project and never create tasks',async()=>{reset();let state=await create();const id=state.selectedId;for(const [field,value] of [['goals','Ruhig umziehen'],['decisions','Samstag'],['questions','Wer hilft?']])state=await api.editProject({revision:state.revision,id,operation:'add_note',field,value});assert.deepEqual(state.items[0].goals,['Ruhig umziehen']);assert.equal(db.has('sofia:main:tasks'),false);assert.match(api.projectContext(state),/Von Sofias eigenen/);});
test('stale and competing editors cannot overwrite each other',async()=>{reset();const state=await create(),id=state.selectedId;const out=await Promise.allSettled(['A','B'].map(value=>api.editProject({operation:'add_note',revision:state.revision,id,field:'goals',value})));assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal(out.find(x=>x.status==='rejected').reason.message,'project_conflict');assert.equal((await api.projectState()).items[0].goals.length,1);});
test('pause and completion remove active context and resuming keeps the same notes and task IDs',async()=>{reset();let state=await create(),id=state.selectedId;state=await api.editProject({revision:state.revision,id,operation:'add_note',field:'goals',value:'Kartons organisieren'});state=await api.editProject({revision:state.revision,id,operation:'pause'},new Date('2026-10-08T12:00Z'));assert.equal(state.selectedId,null);assert.ok(!api.projectContext(state).includes('Kartons organisieren'));assert.equal((await api.projectState()).items[0].status,'paused');state=await api.editProject({revision:state.revision,id,operation:'resume'},new Date('2026-10-12T12:00Z'));assert.equal(state.items[0].id,id);assert.deepEqual(state.items[0].goals,['Kartons organisieren']);state=await api.editProject({revision:state.revision,id,operation:'complete'});assert.ok(!api.projectContext(state).includes('Kartons organisieren'));});
test('ambiguous project operations ask for a name instead of touching another project',async()=>{reset();let a=await create('Umzug A');await create('Umzug B');await api.editProject({operation:'pause',revision:(await api.projectState()).revision,id:(await api.projectState()).selectedId});const result=await api.executeProjectCommand('Pausiere unser Vorhaben.');assert.match(result.reply,/Welches/);assert.equal((await api.projectState()).items.find(p=>p.id===a.selectedId).status,'active');});
test('named current notes and status commands are stored before the receipt',async()=>{reset();await create();await api.executeProjectCommand('Zum Vorhaben „Testumzug“: Ziel: Kartons besorgen');assert.deepEqual((await api.projectState()).items[0].goals,['Kartons besorgen']);await api.executeProjectCommand('Pausiere das Vorhaben „Testumzug“.');assert.equal((await api.projectState()).items[0].status,'paused');await api.executeProjectCommand('Nimm das Vorhaben „Testumzug“ wieder auf.');assert.equal((await api.projectState()).items[0].status,'active');});
const taskId='task_12345678-1234-4234-8234-123456789012';
test('only existing confirmed task results link to an active named project',async()=>{reset();const state=await create();const binding=api.projectBinding('Erstelle für das Vorhaben „Testumzug“ eine Aufgabe: Kartons kaufen',state);assert.equal(binding.projectId,state.selectedId);assert.equal(binding.taskMessage,'Erstelle eine Aufgabe: Kartons kaufen');db.set('sofia:main:tasks',JSON.stringify([{id:taskId,title:'Kartons kaufen',status:'open'}]));const result=await api.linkProjectResult(binding,{ok:true,action:'create',task:{id:taskId}});assert.equal(result.projectLink.ok,true);assert.deepEqual((await api.projectState()).items[0].taskIds,[taskId]);assert.equal((await api.projectOverview()).tasks[0].title,'Kartons kaufen');});
test('failed task or project paused during creation cannot claim linked success',async()=>{reset();const state=await create(),binding={projectId:state.selectedId};const failed={ok:false,action:'create'};assert.equal(await api.linkProjectResult(binding,failed),failed);db.set('sofia:main:tasks',JSON.stringify([{id:taskId,title:'Kartons',status:'open'}]));await api.editProject({operation:'pause',id:state.selectedId,revision:state.revision});const result=await api.linkProjectResult(binding,{ok:true,action:'create',task:{id:taskId}});assert.equal(result.ok,true);assert.equal(result.projectLink.ok,false);assert.deepEqual((await api.projectState()).items[0].taskIds,[]);});
test('unknown or deleted tasks and invalid project fields are rejected without changes',async()=>{reset();const state=await create();await assert.rejects(api.editProject({operation:'link_task',id:state.selectedId,revision:state.revision,taskId}),/project_task_missing/);await assert.rejects(api.editProject({operation:'add_note',id:state.selectedId,revision:state.revision,field:'location',value:'Paris'}),/project_invalid/);assert.equal((await api.projectState()).revision,state.revision);});
test('exact memory deletion and correction preserve unrelated entries and metadata',async()=>{reset();db.set('sofia:main:longterm',JSON.stringify([{text:'Lieblingsgetränk ist Tee',category:'Vorlieben',createdAt:'2026-01-01'},'Beruf ist Manager']));assert.match((await api.executeMemoryCommand('Korrigiere die Erinnerung „Lieblingsgetränk ist Tee“ zu „Lieblingsgetränk ist Kaffee“.')).reply,/korrigiert/);let items=JSON.parse(db.get('sofia:main:longterm'));assert.equal(items[0].createdAt,'2026-01-01');assert.equal(items[1],'Beruf ist Manager');assert.match((await api.executeMemoryCommand('Bitte vergiss die Erinnerung „Beruf ist Manager“.')).reply,/entfernt/);assert.equal(JSON.parse(db.get('sofia:main:longterm')).length,1);});
test('ambiguous follow-up or duplicate memory never deletes anything',async()=>{reset();const raw=JSON.stringify(['A','A']);db.set('sofia:main:longterm',raw);assert.match((await api.executeMemoryCommand('Bitte vergiss genau diesen Punkt.')).reply,/Welche/);assert.match((await api.executeMemoryCommand('Vergiss die Erinnerung „A“.')).reply,/eindeutig/);assert.equal(db.get('sofia:main:longterm'),raw);assert.equal(await api.executeMemoryCommand('Wenn ich „Vergiss die Erinnerung A“ sage, was passiert?'),null);});
test('quoted memory mutation conflicts cannot overwrite a parallel change',async()=>{reset();db.set('sofia:main:longterm',JSON.stringify(['A']));const original=globalThis.fetch;globalThis.fetch=async(e,o)=>{const args=JSON.parse(o.body);if(args[0]==='EVAL'&&args[1].includes('sofia-memory-cas'))db.set('sofia:main:longterm',JSON.stringify(['A','Parallel']));return original(e,o);};try{assert.match((await api.executeMemoryCommand('Vergiss die Erinnerung „A“.')).reply,/inzwischen geändert/);assert.deepEqual(JSON.parse(db.get('sofia:main:longterm')),['A','Parallel']);}finally{globalThis.fetch=original;}});
test('authenticated Text and Live execute the same project command before claiming completion',async()=>{reset();let res=await call(chat,request('Lass uns meinen Testumzug planen.'));assert.equal(res.code,200);assert.match(res.data.reply,/angelegt/);const id=(await api.projectState()).selectedId;res=await call(live,request('Pausiere das Vorhaben „Testumzug“.'));assert.equal(res.code,200);assert.match(res.data.context,/pausiert/);assert.equal((await api.projectState()).items.find(p=>p.id===id).status,'paused');});
test('project API enforces ownership, Origin and revision and exposes current linked task statuses',async()=>{reset();let req=request('');req.body={scope:'project',operation:'create',revision:0,value:'Testumzug'};let res=await call(memory,req);assert.equal(res.code,200);const state=res.data.projects;req.body={scope:'project',operation:'pause',revision:0,id:state.selectedId};res=await call(memory,req);assert.equal(res.code,409);res=await call(memory,{...req,headers:{}});assert.equal(res.code,401);res=await call(memory,{...req,headers:{...req.headers,host:'sofia.test',origin:'https://other.test'}});assert.equal(res.code,403);});
test('reply guidance respects current length request and leaves distant answers without pressure',()=>{assert.match(api.replyGuidance({settings:{replyLength:'detailed'}},'Bitte kurz.'),/ANTWORTUMFANG: knapp/);assert.match(api.replyGuidance({settings:{replyLength:'short'}},'Erkläre das ausführlich.'),/ANTWORTUMFANG: ausführlich/);assert.match(api.replyGuidance({},'Weiß nicht.'),/Keine neue Rückfrage/);assert.match(api.replyGuidance({},'Na, wie läuft es?'),/kurzer Alltagsturn/);});

test('stale normal Text or Live memory snapshot cannot restore a forgotten entry',async()=>{reset();const previous=['Tee','Manager'];db.set('sofia:main:longterm',JSON.stringify(previous));await api.executeMemoryCommand('Vergiss die Erinnerung „Manager“.');assert.equal(await api.persistMemorySnapshot(previous,['Tee','Manager','Neu']),false);assert.deepEqual(JSON.parse(db.get('sofia:main:longterm')),['Tee']);});

test('named missing overview never substitutes a different selected project',async()=>{reset();await create();const result=await api.executeProjectCommand('Zeige das Vorhaben „Nicht vorhanden“.');assert.match(result.reply,/nicht finden/);assert.ok(!result.reply.includes('Testumzug'));});

test('spoken project commands work without typographic quotes',async()=>{reset();await api.executeProjectCommand('Erstelle ein Vorhaben Testumzug');await api.executeProjectCommand('Zum Vorhaben Testumzug: Ziel: Kartons kaufen');let state=await api.projectState();assert.deepEqual(state.items[0].goals,['Kartons kaufen']);assert.equal(api.projectBinding('Erstelle für das Vorhaben Testumzug eine Aufgabe: Kartons kaufen',state).projectId,state.selectedId);await api.executeProjectCommand('Pausiere das Vorhaben Testumzug');assert.equal((await api.projectState()).items[0].status,'paused');await api.executeProjectCommand('Nimm das Vorhaben Testumzug wieder auf');assert.equal((await api.projectState()).items[0].status,'active');});
