import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../sofia-today.js',import.meta.url),'utf8');
function harness(fetcher=async()=>({ok:true,json:async()=>({images:[],tasks:[],life:null})})){
 class Node{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.attrs={};this.listeners={};this.ownText='';this.value='';}get textContent(){return this.ownText+this.children.map(n=>n.textContent).join('');}set textContent(v){this.ownText=v;this.children=[];}get isConnected(){return this.tag==='body'||!!this.parent?.isConnected;}append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n);}}replaceChildren(){this.children=[];this.ownText='';}all(){return this.children.flatMap(n=>[n,...n.all()]);}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.listeners[k]=f;}showModal(){this.open=true;}focus(){this.focused=true;}close(){this.listeners.close?.();}remove(){this.parent.children.splice(this.parent.children.indexOf(this),1);this.parent=null;}}
 const body=new Node('body'),input=new Node('input');input.id='input';body.append(input);const document={body,getElementById:id=>body.all().find(x=>x.id===id),createElement:tag=>new Node(tag),createTextNode:text=>{const n=new Node('text');n.textContent=text;return n;}};const db=new Map(),events={},calls=[],sent=[];const window={SofiaWorkspace:{unreadMessages:()=>[],saveDraft:()=>sent.push('draft')},SofiaSocial:{unreadMessages:()=>[]},addEventListener:(k,f)=>events[k]=f,removeEventListener:k=>delete events[k]};
 vm.runInNewContext(source,{document,window,localStorage:{getItem:k=>db.get(k),setItem:(k,v)=>db.set(k,v)},Date,Intl,Promise,AbortSignal,fetch:async(url,options)=>{calls.push({url,options});return fetcher(url,options);},requestAnimationFrame:f=>f()});return{api:window.SofiaToday,body,document,window,input,db,events,calls,sent};
}
test('Today uses Hamburg calendar boundaries including summer and winter time',()=>{const h=harness();assert.equal(h.api.day('2026-10-08T22:05Z'),'2026-10-09');assert.equal(h.api.day('2026-12-08T22:05Z'),'2026-12-08');assert.equal(h.api.day('2026-12-08T23:05Z'),'2026-12-09');});
test('Today excludes pending, deleted, expired, unpublished and other-day photos and completed tasks',()=>{const h=harness(),at='2026-10-08T22:05Z';const view=h.api.model({images:[{id:'a',sentAt:at},{id:'a',sentAt:at},{id:'b',sentAt:at,status:'pending'},{id:'c',sentAt:'2026-10-08T10:00Z'},{id:'d',sentAt:at,published:false},{id:'e',sentAt:at,status:'expired'},{id:'f',sentAt:at,deleted:true}],tasks:[{id:'t1',status:'open',dueAt:at},{id:'t2',status:'completed',dueAt:at},{id:'t3',status:'open',dueAt:'2026-10-08T10:00Z'}]},new Date(at));assert.deepEqual(Array.from(view.photos,x=>x.id),['a']);assert.deepEqual(Array.from(view.tasks,x=>x.id),['t1']);});
test('sections preserve deliberate false choices and reject malformed values',()=>{const h=harness();assert.equal(h.api.normalize({photos:false}).photos,false);assert.equal(h.api.normalize({photos:'false'}).photos,true);assert.equal(h.api.normalize().tasks,true);});
test('parallel overview refresh is coalesced and uses GET only',async()=>{const h=harness();const a=h.api.refresh(),b=h.api.refresh();await Promise.all([a,b]);assert.equal(h.calls.length,2);assert.deepEqual(h.calls.map(x=>x.url),['/api/chat','/api/tasks?status=open']);assert.ok(h.calls.every(x=>!x.options.method&&!x.options.body));assert.equal(h.sent.length,0);});
test('partial refresh failure preserves earlier photos and does not replay any action',async()=>{let fail=false;const h=harness(async url=>({ok:!(fail&&url==='/api/chat'),json:async()=>url==='/api/chat'?{images:[{id:'a',sentAt:new Date().toISOString()}],life:null}:{tasks:[]}}));h.api.open();await new Promise(r=>setImmediate(r));assert.match(h.body.textContent,/Foto öffnen/);fail=true;const update=h.body.all().find(x=>x.textContent==='Aktualisieren');await update.onclick();await new Promise(r=>setImmediate(r));assert.match(h.body.textContent,/Nicht vollständig aktualisiert/);assert.match(h.body.textContent,/Foto öffnen/);assert.equal(h.sent.length,0);assert.equal(h.calls.length,4);});
test('open topics prepare a draft only after explicit choice and never replace an existing draft',async()=>{const h=harness(async url=>({ok:true,json:async()=>url==='/api/chat'?{images:[],life:{threads:[{topic:'Prüfung',status:'open',expiresAt:new Date(Date.now()+86400000).toISOString()}]}}:{tasks:[]}}));h.api.open();await new Promise(r=>setImmediate(r));const topic=h.body.all().find(x=>x.tag==='button'&&x.textContent==='Prüfung');h.input.value='mein Entwurf';topic.onclick();assert.equal(h.input.value,'mein Entwurf');assert.equal(h.sent.length,0);h.input.value='';topic.onclick();assert.equal(h.input.value,'Lass uns über Prüfung weiterreden.');assert.deepEqual(h.sent,['draft']);});
test('opening Today does not mark messages read and uses the contact ledger for the count',async()=>{const h=harness();let opened=null;h.window.SofiaSocial.unreadMessages=()=>[{id:'contact',text:'Hallo',createdAt:new Date().toISOString()}];h.window.SofiaSocial.unreadCount=()=>1;h.api.open();await new Promise(r=>setImmediate(r));assert.match(h.body.textContent,/Neue Nachrichten \(1\)/);assert.equal(opened,null);assert.equal(h.sent.length,0);});

test('a pending duplicate never hides a completed photo from Today',()=>{const h=harness(),now=new Date();const view=h.api.model({images:[{id:'a',sentAt:now.toISOString(),status:'pending'},{id:'a',sentAt:now.toISOString(),status:'done'}]},now);assert.equal(view.photos.length,1);assert.equal(view.photos[0].status,'done');});
