import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../sofia-workspace.js',import.meta.url),'utf8');
function harness(saved={}){
 class Node{
  constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.style={};this.className='';this.hidden=false;this.value='';this.text='';this.listeners={};this.scrollTop=100;this.scrollHeight=200;this.clientHeight=100;}
  get textContent(){return this.text+this.children.map(n=>n.textContent).join('');}set textContent(t){this.text=t;this.children=[];}
  get classList(){return{contains:c=>this.className.split(' ').includes(c),add:c=>this.className+=' '+c,remove:c=>this.className=this.className.split(' ').filter(x=>x!==c).join(' ')};}
  append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n);}}
  insertBefore(n,b){n.parent=this;this.children.splice(this.children.indexOf(b),0,n);}
  replaceChildren(){this.children=[];}
  all(){return this.children.flatMap(n=>[n,...n.all()]);}
  querySelectorAll(s){return this.all().filter(n=>s==='.msg[data-created-at]'?n.classList.contains('msg')&&n.dataset.createdAt: s.startsWith('.')&&n.classList.contains(s.slice(1)));}
  querySelector(s){return this.querySelectorAll(s)[0]||null;}
  setAttribute(k,v){this[k]=v;}
  addEventListener(t,f){this.listeners[t]=f;}
  focus(){this.focused=true;}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}remove(){if(this.parent)this.parent.children.splice(this.parent.children.indexOf(this),1);}scrollIntoView(o){this.scrolled=o;}
 }
 const db=new Map(Object.entries(saved).map(([k,v])=>[k,JSON.stringify(v)])),localStorage={getItem:k=>db.get(k),setItem:(k,v)=>db.set(k,v)};
 const body=new Node('body'),html=new Node('html');for(const id of ['messages','input','mode','connectionStatus','chatLatest','workspaceAction']){const n=new Node(id==='input'?'textarea':'div');n.id=id;body.append(n);}
 const events={},document={body,documentElement:html,visibilityState:'visible',getElementById:id=>body.all().find(n=>n.id===id)||null,querySelector:s=>s.includes('dialog[open]')?body.all().find(n=>n.tagName==='DIALOG'&&n.open):null,createElement:t=>new Node(t),addEventListener:(t,f)=>events[t]=f};
 const window={location:{reload(){window.reloaded=true;}},addEventListener:(t,f)=>events[t]=f,SofiaUI:{resizeComposer(){},enhanceDialog(){}},matchMedia:()=>({matches:false})},navigator={serviceWorker:{controller:{},addEventListener:(t,f)=>events[t]=f},onLine:true,clipboard:{writeText:async()=>{}}};
 vm.runInNewContext(source,{window,document,navigator,localStorage,Map,Set,Intl,Date,setTimeout:()=>1,clearTimeout(){},requestAnimationFrame:f=>f()});
 const message=turn=>{const n=new Node('div');n.className='msg '+(turn.role==='user'?'user':'sofia');n.dataset.messageText=turn.content;n.dataset.createdAt=turn.createdAt;n.textContent=turn.content;document.getElementById('messages').append(n);return n;};
 return{api:window.SofiaWorkspace,window,document,events,db,navigator,input:document.getElementById('input'),root:document.getElementById('messages'),message};
}
test('draft survives reload, remains pending until receipt and returns after failed submission',()=>{
 const h=harness({'sofia_draft_v448':{text:'Entwurf\nzweite Zeile'}});assert.equal(h.input.value,'Entwurf\nzweite Zeile');h.api.beginSubmission(h.input.value);h.input.value='';h.events.pagehide();assert.equal(JSON.parse(h.db.get('sofia_draft_v448')).text,'');assert.equal(JSON.parse(h.db.get('sofia_draft_v448')).pending.text,'Entwurf\nzweite Zeile');h.api.failSubmission('Entwurf\nzweite Zeile');assert.equal(h.input.value,'Entwurf\nzweite Zeile');h.api.beginSubmission(h.input.value);h.input.value='';h.api.confirmSubmission('Entwurf\nzweite Zeile');assert.equal(JSON.parse(h.db.get('sofia_draft_v448')).text,'');
});
test('a photo reply never clears a separate text draft',()=>{const h=harness({'sofia_draft_v448':{text:'mein Entwurf'}});h.api.confirmSubmission('Dieses Foto anpassen');assert.equal(JSON.parse(h.db.get('sofia_draft_v448')).text,'mein Entwurf');});
test('stored preferences are validated and local surface motion stays separate from avatar settings',()=>{const h=harness({'sofia_ui_v448':{font:'large',density:'compact',motion:'off'}});assert.equal(h.document.documentElement.dataset.chatFont,'large');assert.equal(h.api.motion(),'auto');assert.equal(h.document.documentElement.dataset.presenceMotion,undefined);assert.deepEqual(JSON.parse(JSON.stringify(h.api.normalize({font:'huge',motion:'broken'}))),{font:'normal',density:'comfortable',motion:'auto'});});
test('search returns only matching text and jumps without submitting any message',()=>{
 const h=harness();const t={role:'assistant',content:'Ein Kaffee an der Alster',createdAt:'2026-10-08T10:00:00Z'},n=h.message(t);h.message({role:'user',content:'Ganz anderer Text',createdAt:'2026-10-08T10:01:00Z'});h.api.search();const d=h.document.body.all().find(n=>n.tagName==='DIALOG'),field=d.all().find(n=>n.type==='search');field.value='KAFFEE';field.oninput();assert.ok(d.textContent.includes('1 Treffer'));d.all().find(n=>n.textContent==='Im Chat anzeigen').onclick();assert.equal(n.scrolled.block,'center');
});
test('pins retain exact text and timestamp after local reload without a memory API call',()=>{
 const h=harness(),turn={role:'assistant',content:'wichtige Nachricht',createdAt:'2026-10-08T10:00:00Z'},n=h.message(turn);h.api.refresh();n.all().find(x=>x.className==='message-menu').onclick();let d=h.document.body.all().find(n=>n.tagName==='DIALOG');d.all().find(n=>n.textContent==='Nachricht anheften').onclick();const persisted=JSON.parse(h.db.get('sofia_pins_v448'));assert.equal(persisted[0].content,turn.content);assert.equal(persisted[0].createdAt,turn.createdAt);const next=harness({'sofia_pins_v448':persisted});next.api.pinned();assert.match(next.document.body.textContent,/wichtige Nachricht/);
});
test('unread ledger counts once across history refresh and clears only at visible latest',()=>{
 const h=harness({'sofia_read_at_v448':0}),turn={role:'assistant',content:'neu',createdAt:'2026-10-08T10:00:00Z'};h.root.scrollTop=0;h.message(turn);h.api.reconcile([turn],[]);h.api.refresh();assert.match(h.document.getElementById('chatLatest')['aria-label'],/1 ungelesen/);h.api.reconcile([turn],[turn]);h.api.refresh();assert.match(h.document.getElementById('chatLatest')['aria-label'],/1 ungelesen/);h.api.readVisible();assert.match(h.document.getElementById('chatLatest')['aria-label'],/1 ungelesen/);h.root.scrollTop=100;h.document.visibilityState='hidden';h.api.readVisible();assert.match(h.document.getElementById('chatLatest')['aria-label'],/1 ungelesen/);h.document.visibilityState='visible';h.api.readVisible();assert.equal(h.document.getElementById('chatLatest').textContent,'↓');
});
test('unknown transport and task results never offer a one-click resend',()=>{
 const h=harness();assert.equal(h.api.safeRetry('Erstelle eine Aufgabe',false,false),false);assert.equal(h.api.safeRetry('Wie geht es dir?',true,false),false);const node=h.message({role:'assistant',content:'Fehler',createdAt:'2026-10-08T10:00:00Z'});h.api.failed(node,'Erstelle eine Aufgabe',{uncertain:true,knownRejected:true});assert.equal(node.all().at(-1).textContent,'Entwurf wiederherstellen');node.all().at(-1).onclick();assert.match(h.document.getElementById('connectionStatus').textContent,/Aufgabenstand/);assert.equal(h.input.value,'Erstelle eine Aufgabe');
});
test('explicit rejection of a plain text request allows retry only when sender accepts',()=>{
 const h=harness(),node=h.message({role:'assistant',content:'kurz warten',createdAt:'2026-10-08T10:00:00Z'});let sent=0;h.window.SofiaChatSend=()=>{sent++;return false;};h.api.failed(node,'Wie geht es dir?',{knownRejected:true});const retry=node.all().at(-1);assert.equal(retry.textContent,'Nachricht erneut senden');retry.onclick();assert.notEqual(retry.disabled,true);h.window.SofiaChatSend=()=>{sent++;return true;};retry.onclick();assert.equal(retry.disabled,true);assert.equal(sent,2);
});

test('PWA update waits for idle state, saves draft and never resends a message',async()=>{
 const h=harness();h.events.controllerchange();h.input.value='Noch nicht gesendet';h.api.settings();
 const action=h.document.body.all().find(n=>n.textContent==='Neue Version laden');assert.ok(action);
 h.document.getElementById('mode').dataset.phase='photo';await action.onclick();assert.equal(h.window.reloaded,undefined);
 h.document.getElementById('mode').dataset.phase='ready';h.window.SofiaCharacterSettings={flush:async()=>false};await action.onclick();assert.equal(h.window.reloaded,undefined);
 h.window.SofiaCharacterSettings.flush=async()=>true;await action.onclick();assert.equal(h.window.reloaded,true);assert.ok([...h.db.values()].some(v=>v.includes('Noch nicht gesendet')));
});

test('overview exposes unread turns without reading and can jump to the exact message',()=>{const h=harness({'sofia_read_at_v448':0}),turn={role:'assistant',content:'neue Nachricht',createdAt:'2026-10-08T10:00Z'},node=h.message(turn);h.api.reconcile([turn],[]);assert.equal(h.api.unreadMessages().length,1);assert.equal(h.api.messages()[0].content,turn.content);assert.equal(h.api.showMessage(turn),true);assert.equal(node.scrolled.block,'center');assert.equal(h.api.unreadMessages().length,1);assert.equal(h.api.showMessage({...turn,content:'andere'}),false);});

test('server contact read receipts reconcile local unread without reading unrelated messages',()=>{const h=harness({'sofia_read_at_v448':0}),contact={role:'assistant',content:'Eigeninitiative',contactId:'contact',createdAt:'2026-10-08T10:00Z'},normal={role:'assistant',content:'normale Antwort',createdAt:'2026-10-08T10:01Z'};h.api.reconcile([contact,normal],[]);assert.equal(h.api.unreadMessages().length,2);h.api.acknowledgeContacts(['contact']);assert.equal(h.api.unreadMessages().length,1);assert.equal(h.api.unreadMessages()[0].content,normal.content);h.api.acknowledgeContacts(['other']);assert.equal(h.api.unreadMessages().length,1);});


test('closing during submission parks it outside the composer and server receipt clears it after reopening',()=>{
 const h=harness();h.api.beginSubmission('PWA Versandprobe');h.events.pagehide();const persisted=JSON.parse(h.db.get('sofia_draft_v448'));assert.equal(persisted.text,'');assert.equal(persisted.pending.text,'PWA Versandprobe');
 const reopened=harness({'sofia_draft_v448':persisted});assert.equal(reopened.input.value,'');const at=new Date(persisted.pending.at+500).toISOString();assert.equal(reopened.api.reconcileSubmission([{role:'user',content:'PWA Versandprobe',createdAt:at},{role:'assistant',content:'Bestätigt',createdAt:at}]),true);reopened.events.pagehide();assert.equal(JSON.parse(reopened.db.get('sofia_draft_v448')).pending,undefined);assert.equal(harness({'sofia_draft_v448':JSON.parse(reopened.db.get('sofia_draft_v448'))}).input.value,'');
});
test('a historical identical message and optimistic local history are not a delivery receipt',()=>{
 const h=harness();h.api.beginSubmission('Noch einmal');const at=JSON.parse(h.db.get('sofia_draft_v448')).pending.at;
 assert.equal(h.api.reconcileSubmission([{role:'user',content:'Noch einmal',createdAt:new Date(at-86400000).toISOString()},{role:'assistant',content:'Alt'}]),false);
 assert.equal(h.api.reconcileSubmission([{role:'user',content:'Noch einmal',createdAt:new Date(at).toISOString()}]),false);assert.ok(JSON.parse(h.db.get('sofia_draft_v448')).pending);
});
test('a fresh unsent draft survives the receipt for an earlier parked submission',()=>{
 const h=harness();h.api.beginSubmission('gesendet');const at=JSON.parse(h.db.get('sofia_draft_v448')).pending.at;h.input.value='neuer Entwurf';h.events.input?.();h.events.pagehide();
 const reopen=harness({'sofia_draft_v448':JSON.parse(h.db.get('sofia_draft_v448'))});assert.equal(reopen.input.value,'neuer Entwurf');reopen.api.reconcileSubmission([{role:'user',content:'gesendet',createdAt:new Date(at).toISOString()},{role:'assistant',content:'Antwort'}]);assert.equal(reopen.input.value,'neuer Entwurf');assert.equal(JSON.parse(reopen.db.get('sofia_draft_v448')).text,'neuer Entwurf');
});
test('unconfirmed parked submission can only be restored by explicit gesture and cannot overwrite a draft',()=>{
 const h=harness();h.api.beginSubmission('noch unbestätigt');h.api.pendingSubmission();const d=h.document.body.all().find(n=>n.tagName==='DIALOG'),recover=d.all().find(n=>n.textContent==='Als Entwurf übernehmen');h.input.value='anderer Entwurf';recover.onclick();assert.equal(h.input.value,'anderer Entwurf');h.input.value='';recover.onclick();assert.equal(h.input.value,'noch unbestätigt');assert.equal(JSON.parse(h.db.get('sofia_draft_v448')).pending,undefined);
});
test('server reconciliation happens before an unchanged-history early return',async()=>{
 const app=await readFile(new URL('../app.js',import.meta.url),'utf8');assert.ok(app.indexOf('reconcileSubmission(serverHistory)')<app.indexOf('signature === lastServerHistorySignature'));
});

test('unknown transport outcome stays parked across closure rather than returning as an unsent draft',()=>{
 const h=harness();h.api.beginSubmission('möglicherweise zugestellt');h.api.failSubmission('möglicherweise zugestellt',{uncertain:true});h.events.pagehide();const stored=JSON.parse(h.db.get('sofia_draft_v448'));assert.equal(stored.text,'');assert.equal(stored.pending.text,'möglicherweise zugestellt');assert.equal(harness({'sofia_draft_v448':stored}).input.value,'');
});

test('stale window cannot resurrect a confirmed pending submission on pagehide',()=>{const first=harness();first.api.beginSubmission('Einmal gesendet');const stale=harness({'sofia_draft_v448':JSON.parse(first.db.get('sofia_draft_v448'))});first.api.confirmSubmission('Einmal gesendet');stale.db.set('sofia_draft_v448',first.db.get('sofia_draft_v448'));stale.events.pagehide();assert.equal(JSON.parse(stale.db.get('sofia_draft_v448')).pending,undefined);});
test('background saves unsent draft and retains a newer cross-window pending request without sending',()=>{const h=harness();let sends=0;h.window.SofiaChatSend=()=>sends++;h.input.value='Mein neuer Entwurf';h.document.visibilityState='hidden';h.events.visibilitychange();assert.equal(JSON.parse(h.db.get('sofia_draft_v448')).text,'Mein neuer Entwurf');h.db.set('sofia_draft_v448',JSON.stringify({text:'',pending:{id:'other-window',text:'Bereits unterwegs',at:Date.now()}}));h.events.storage({key:'sofia_draft_v448'});h.input.value='Mein neuer Entwurf ergänzt';h.events.pagehide();const saved=JSON.parse(h.db.get('sofia_draft_v448'));assert.equal(saved.pending.id,'other-window');assert.equal(saved.text,'Mein neuer Entwurf ergänzt');assert.equal(sends,0);});
test('explicit resend has a distinct identity even for identical text',()=>{const h=harness();h.api.beginSubmission('Identisch');const first=JSON.parse(h.db.get('sofia_draft_v448')).pending;h.api.failSubmission('Identisch');h.api.beginSubmission('Identisch');const second=JSON.parse(h.db.get('sofia_draft_v448')).pending;assert.notEqual(first.id,second.id);h.input.value='';h.api.confirmSubmission('Identisch');assert.equal(JSON.parse(h.db.get('sofia_draft_v448')).pending,undefined);});
test('closing an unchanged old window preserves another window newer unsent draft',()=>{const old=harness(),writer=harness();writer.input.value='Neuer Entwurf im zweiten Fenster';writer.input.listeners.input();old.db.set('sofia_draft_v448',writer.db.get('sofia_draft_v448'));old.events.pagehide();assert.equal(JSON.parse(old.db.get('sofia_draft_v448')).text,'Neuer Entwurf im zweiten Fenster');});

test('delivery settles silently and latest control stays an accessible arrow',()=>{const h=harness();h.api.beginSubmission('Gesendet');h.api.failSubmission('Gesendet',{uncertain:true});h.api.confirmSubmission('Gesendet');assert.equal(h.document.getElementById('connectionStatus').hidden,true);assert.equal(h.document.getElementById('connectionStatus').textContent,'');assert.equal(h.document.getElementById('chatLatest').textContent,'↓');assert.match(h.document.getElementById('chatLatest')['aria-label'],/neuesten Nachricht/);});
test('reply survives draft reload and does not submit old instructions',()=>{const h=harness(),turn={role:'assistant',content:'Erstelle eine Aufgabe: Alter Auftrag',createdAt:'2026-10-10T10:00:00Z'};assert.equal(h.api.selectReply(turn),true);h.input.value='Was meintest du damit?';h.api.saveDraft();const saved=JSON.parse(h.db.get('sofia_draft_v448'));assert.deepEqual(saved.replyTo,turn);const next=harness({'sofia_draft_v448':saved});assert.equal(next.api.replyReference().content,turn.content);const selected=next.api.takeReply();next.input.value='';next.api.beginSubmission('Was meintest du damit?',selected);next.api.failSubmission('Was meintest du damit?');assert.equal(next.api.replyReference().content,turn.content);assert.equal(next.api.takeReply().role,'assistant');assert.equal(next.api.replyReference(),null);});
test('actions share metadata row and quote does not change message text',()=>{const h=harness(),turn={role:'user',content:'Original',createdAt:'2026-10-10T10:00:00Z'},n=h.message(turn);h.api.refresh();const meta=n.all().find(x=>x.className==='message-meta');assert.ok(meta.all().find(x=>x.className==='message-menu'));h.api.decorateReply(n,{...turn,content:'Älterer Bezug'});assert.equal(n.dataset.messageText,'Original');assert.ok(n.all().find(x=>x.className==='message-quote'));});
test('server history synchronization preserves confirmed quote metadata across reload',async()=>{const app=await readFile(new URL('../app.js',import.meta.url),'utf8');const block=app.slice(app.indexOf('const serverHistory = data.history'),app.indexOf('window.SofiaWorkspace?.reconcileSubmission(serverHistory)'));const quote={role:'assistant',content:'Ältere Nachricht',createdAt:'2026-10-09T10:00:00Z'};const result=vm.runInNewContext('(()=>{'+block+'return serverHistory;})()',{data:{history:[{role:'user',content:'Meine Antwort',createdAt:'2026-10-10T10:00:00Z',replyTo:quote}]},MAX_STORED_MESSAGES:120});assert.equal(result[0].replyTo.content,quote.content);assert.equal(result[0].content,'Meine Antwort');});

test('confirmed hidden turns leave pins, unread, draft reference and local mirror',()=>{const t={role:'assistant',content:'Nachricht zum Ausblenden',createdAt:'2026-10-09T10:00:00Z'},h=harness({'sofia_pins_v448':[t],'sofia_draft_v448':{text:'Antwort',replyTo:t}});h.api.acceptHidden([t]);assert.equal(h.api.replyReference(),null);assert.equal(h.input.value,'Antwort');assert.equal(h.api.filterHistory([t]).length,0);assert.equal(JSON.parse(h.db.get('sofia_pins_v448')).length,0);const after=harness({'sofia_hidden_chat_v478':[t]});assert.equal(after.api.isHidden(t),true);});
test('message action deletion uses exact source and closes only after successful server acknowledgment',async()=>{const h=harness(),t={role:'user',content:'Löschprobe',createdAt:'2026-10-09T10:00:00Z'},n=h.message(t);let selected;h.window.SofiaChatDelete=async value=>selected=value;h.api.refresh();n.querySelector('.message-menu').onclick();const d=h.document.body.all().find(x=>x.tagName==='DIALOG');await d.all().find(x=>x.textContent==='Nachricht löschen').onclick();assert.equal(selected.content,t.content);assert.equal(selected.createdAt,t.createdAt);assert.equal(d.open,false);assert.doesNotMatch(h.document.getElementById('connectionStatus').textContent,/gelöscht/);});
test('failed message deletion keeps the menu and reports error, without deleting locally',async()=>{const h=harness(),t={role:'user',content:'Bleibt erhalten',createdAt:'2026-10-09T10:00:00Z'},n=h.message(t);h.window.SofiaChatDelete=async()=>{throw Error('Offline');};h.api.refresh();n.querySelector('.message-menu').onclick();const d=h.document.body.all().find(x=>x.tagName==='DIALOG'),b=d.all().find(x=>x.textContent==='Nachricht löschen');await b.onclick();assert.equal(d.open,true);assert.equal(b.disabled,false);assert.match(d.textContent,/Offline/);assert.equal(h.api.isHidden(t),false);});
test('embedded quote has sender, German date and text inside the message',()=>{const h=harness(),t={role:'user',content:'Der Bezug',createdAt:'2026-10-09T10:00:00Z'},n=h.message({...t,content:'Meine Antwort'});h.api.decorateReply(n,t);const quote=n.querySelector('.message-quote');assert.match(quote.textContent,/09.10.2026/);assert.match(quote.textContent,/Du/);assert.match(quote.textContent,/Der Bezug/);assert.equal(n.dataset.messageText,'Meine Antwort');});
test('photo selection retains exact image id in the persisted draft',()=>{const h=harness(),t={role:'assistant',content:'Foto',createdAt:'2026-10-09T10:00:00Z',imageId:'11111111-1111-4111-8111-111111111111'};h.api.selectReply(t);assert.equal(JSON.parse(h.db.get('sofia_draft_v448')).replyTo.imageId,t.imageId);});
test('task preparation does not create a task before user selects save',()=>{const h=harness();h.api.taskFromMessage({role:'user',content:'Bericht prüfen',createdAt:'2026-10-09T10:00:00Z'});assert.match(h.document.body.textContent,/Aufgabe speichern/);assert.equal(h.document.body.all().find(x=>x['aria-label']==='Aufgabentitel').value,'Bericht prüfen');});
